Field-tested updates (fixes)

diff --git a/create_image b/create_image
--- a/create_image
+++ b/create_image
@@ -1,6 +1,8 @@
 #!/bin/bash
 
-if [ "$#" != "1" ]; then
+set -e  # Fail immediately if any of the commands below fail
+
+if [ "$#" != "2" ]; then
     echo \
 "Usage: $0 TARGET path/to/config.conf
 
@@ -34,7 +36,7 @@ if [ ! "$arch" -o \
     exit 1
 fi
 
-export LANG=C
+export LANG=C LC_ALL=C
 export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true DEBIAN_PRIORITY=critical  # don't ask any questions
 
 # Install the minimum base
@@ -49,32 +51,38 @@ $apt_source_lines
 EOF
 
 # Prepare the chroot for installing
-mount --bind /bin/true          "$CHROOT"/usr/bin/ischroot
-mount --bind /etc/resolv.conf   "$CHROOT"/etc/resolv.conf
-mount --bind /proc/mounts       "$CHROOT"/etc/mtab
 for fs in dev proc sys; do mount --bind /$fs "$CHROOT"/$fs ; done
-echo -e "#!/bin/sh\nexit 101" > "$CHROOT"/usr/sbin/policy-rc.d && chmod a+x "$CHROOT"/usr/sbin/policy-rc.d
+mount --bind /bin/true          "$CHROOT"/usr/bin/ischroot
+cp           /etc/resolv.conf   "$CHROOT"/etc/resolv.conf
+cp           /proc/mounts       "$CHROOT"/etc/mtab
+echo -e '#!/bin/sh\nexit 101' > "$CHROOT"/usr/sbin/policy-rc.d && chmod a+x "$CHROOT"/usr/sbin/policy-rc.d
 
-# Do the magic
+# Prepare this for grub (BUG on Ubuntu)
+mkdir -p /boot/grub
+touch /boot/grub/menu.lst
+
+# Install packages
 chroot "$CHROOT" apt-get -qqyy update
 chroot "$CHROOT" apt-get -yy install $packages
 # Run the post-installation scripts
 if [ "$scripts" ]; then
     mkdir -p "$CHROOT/tmp/$scripts"
     mount --bind "$scripts" "$CHROOT/tmp/$scripts"
-    chroot "$CHROOT" run-parts --verbose --exit-on-error "$scripts"
-    umount "$CHROOT"/tmp
+    chroot "$CHROOT" run-parts --verbose --exit-on-error "/tmp/$scripts"
+    umount "$CHROOT/tmp/$scripts"
 fi
 
 # Unprepare the chroot
 rm "$CHROOT"/usr/sbin/policy-rc.d
-for fs in dev proc sys; do umount "$CHROOT"/$fs ; done
-umount "$CHROOT"/etc/mtab
-umount "$CHROOT"/etc/resolv.conf
+rm "$CHROOT"/etc/mtab
+echo > "$CHROOT"/etc/resolv.conf
 umount "$CHROOT"/usr/bin/ischroot
+umount "$CHROOT"/{dev,proc,sys}
 
 # Clean the directories
 rm -r "$CHROOT"/{tmp,var/tmp,dev,proc,sys,media,mnt,run}/*
 
 # Compress the chroot directory
-tar --exclude-backups -C "$CHROOT" -cf- . | gzip --fast --stdout > "$output_archive"
+echo 'Compressing image ...'
+tar --exclude-backups -C "$CHROOT" -cf- . |
+    gzip --fast --stdout > "$output_archive"
diff --git a/install_depends b/install_depends
--- a/install_depends
+++ b/install_depends
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -e  # Fail immediately if any of the commands below fail
+
 DEPENDENCIES="
 coreutils
 sed
@@ -15,11 +17,12 @@ parted
 e2fsprogs
 mount
 util-linux
+# for create_image
+debootstrap
 "
 
-if [ $EUID -gt 500 ]; then
-    echo "Error: You are not root."
-    exit 1
-fi
+PACKAGES="$(echo "$DEPENDENCIES" | awk '/^ *[^# ]/{print $1}')"
 
-apt-get install $(echo "$DEPENDENCIES" | awk '/^ *[^# ]/{print $1}')
+echo "Installing packages: "$PACKAGES
+
+apt-get install $PACKAGES
diff --git a/parts/assess_disk b/parts/assess_disk
--- a/parts/assess_disk
+++ b/parts/assess_disk
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e  # Fail immediately if any of the commands below fail
+
 if [ "$#" != "1" ]; then
     echo \
 "Usage: $0 /dev/sdX
@@ -39,7 +41,7 @@ value=$(get_smart_data | awk '{ print $10 }' |
 if [ "$value" = '0' ]; then
     echo ''
     smartctl --info $DISK |
-        awk '/^Device Model|Serial Number|User Capacity/{ print $0\n }END{ print "\n" }' |
+        awk '/^Device Model|Serial Number|User Capacity/{ print $0 }END{ print "\n" }' |
         tee -a "$LOG_FILE"
     echo "(also appended to $LOG_FILE)"
 else
diff --git a/parts/wipe_disk b/parts/wipe_disk
--- a/parts/wipe_disk
+++ b/parts/wipe_disk
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e  # Fail immediately if any of the commands below fail
+
 if [ "$#" != "1" ]; then
     echo \
 "Usage: $0 /dev/sdX
@@ -17,26 +19,30 @@ DISK="$1"
 
 # From https://wiki.archlinux.org/index.php/Securely_wipe_disk#Advanced_example
 
-DISK_SIZE=$(df -B1 $DISK | tail -n1 | tr -s ' ' | cut -d' ' -f2)
+DISK_SIZE=$(lsblk --output SIZE --bytes --noheadings --nodeps $DISK)
 PHYS_BLOCK_SIZE=$(cat /sys/block/$(basename $DISK)/queue/physical_block_size)
 NUM_BLOCKS=$((DISK_SIZE / PHYS_BLOCK_SIZE))
-random_pass() { dd if=/dev/random bs=128 count=1 2>/dev/null | base64; }
+random_password() { dd if=/dev/random bs=128 count=1 2>/dev/null | base64; }
 
-# TODO: account for effective writing speed
+# TODO: account for effective writing speed: if too low, disk is crap.
+
+_write_stdin_with_reporting() {
+    pv -bartpes $DISK_SIZE |
+        dd bs=$PHYS_BLOCK_SIZE count=$NUM_BLOCKS of=$DISK
+}
 write_random() {
     echo "Writing random data to disk: $DISK"
-    openssl enc -aes-256-ctr -pass pass:"$(random_pass)" -nosalt </dev/zero |
-        pv -bartpes $DISK_SIZE |
-        dd bs=$PHYS_BLOCK_SIZE count=$NUM_BLOCKS of=$DISK
+    openssl enc -aes-256-ctr -pass pass:"$(random_password)" -nosalt </dev/zero |
+        _write_stdin_with_reporting
 }
 
 write_zeros() {
     echo "Writing zeros to disk: $DISK"
     cat /dev/zero |
-        pv -bartpes $DISK_SIZE |
-        dd bs=$PHYS_BLOCK_SIZE count=$NUM_BLOCKS of=$DISK
+        _write_stdin_with_reporting
 }
 
-for func in write_random write_random write_zeros; do
+for func in write_random \
+            write_zeros; do
     $func
 done
